pipeline {
    agent any
    stages {
        stage('Build, Test and Package') {
            steps {
                git 'https://github.com/tnguyen84106/MyJenkinsApp.git'
                sh "jmeter -Jjmeter.save.saveservice.output_format=xml -n -t jmeter/MyJenkinsApp.jmx -l jmeter/MyJenkinsApp.jtl"
            }
            post{
                success{
                    sh "echo 'Success!!!'"
                    archiveArtifacts artifacts: 'jmeter/MyJenkinsApp.jtl'
                    perfReport 'jmeter/MyJenkinsApp.jtl'
                }
            }
        }
    }
}